name: Oracle Capacity Sniper
on:
  schedule:
    - cron: '*/30 * * * *' # Tries every 30 mins, 24/7
  workflow_dispatch:      # Allows you to click "Run" manually

jobs:
  snipe:
    runs-on: ubuntu-latest
    env:
      OCI_CLI_USER: ${{ secrets.OCI_USER_OCID }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_TENANCY_OCID }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_REGION }}
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

    steps:
      - name: Launch Instance
        uses: oracle-actions/run-oci-cli-command@v1.3.2
        with:
          command: |
            compute instance launch \
            --availability-domain "LAtS:US-CHICAGO-1-AD-1" \
            --compartment-id "PASTE_YOUR_COMPARTMENT_OCID_HERE" \
            --shape "VM.Standard.A1.Flex" \
            --shape-config '{"ocpus":4,"memoryInGBs":24}' \
            --subnet-id "PASTE_YOUR_SUBNET_OCID_HERE" \
            --image-id "ocid1.image.oc1.us-chicago-1.aaaaaaaardyalqgy2m4yenctp5x54zmoukyhurifsae7zqwk345sekcircrq" \
            --assign-public-ip true \
            --ssh-authorized-keys-file "PASTE_YOUR_PUBLIC_SSH_KEY_TEXT_HERE" \
            --display-name "AI-Server"
